name: Deploy to Dev Channel

on:
  push:
    branches:
      - dev # Se activa al subir cambios a dev

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    environment: development

    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL_DEV || secrets.VITE_API_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install and Build
        run: npm i && npm run build

      - name: Deploy to Firebase Dev Site
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_TOKEN }}"
          projectId: cb-wallet-70da0
          target: dev
          channelId: live
